### ISSUE TITLE
I can't find the .py file that corresponding to optimization of molecules via properties using GP

### ISSUE THREAD

**Issue by SupernovaTitanium** [aspuru-guzik-group/chemical_vae#11]
Dear jnwei:

I am interesting in real-world application of Bayesian Optimization. I see that in the introduction of your paper ， you state " Gradient-based optimization can be combined with Bayesian optimization methods to select compounds that are likely to be informative about the global optimum." and you also say you use GP to optimize the surrogate property predictor. I think the description in the paper is a little bit vague that I can't recognize how you actually use GP， could you specify the file that you use the GP? I really can't find it.

Thanks

Wei-Cheng

**Comment by jnwei** [comment]
Hi Wei-Cheng,

The Gaussian Process optimization method is not released in this repo.
However, if you're interested in Bayesian optimization in chemistry, I'd
encourage you to keep an eye out for aspuru-guzik-group/gpmol, which will
be released soon.

Jennifer
